local json = require("json")
Creator = Creator or ""
TotalDeposit = TotalDeposit or "0"
MarketInfo = MarketInfo or {}
Handlers.add("GetProcessOwner", Handlers.utils.hasMatchingTag("Action", "GetProcessOwner"), function(msg)
    print("GetProcessOwner")
    ao.send({ Target = msg.From, Data = ao.env.Process.Owner })
end)
Handlers.add("GetOwner", Handlers.utils.hasMatchingTag("Action", "GetOwner"), function(msg)
    print("GetOwner")
    ao.send({ Target = msg.From, Data = Owner })
end)
Handlers.add("GetCreator", Handlers.utils.hasMatchingTag("Action", "GetCreator"), function(msg)
    print("GetCreator")
    ao.send({ Target = msg.From, Data = Creator })
end)
Handlers.add("Deposit", Handlers.utils.hasMatchingTag("Action", "Deposit"), function(msg)
    print("Deposit")
    ao.send({ Target = msg.From, Data = "Deposit" })
end)
Handlers.add("Withdraw", Handlers.utils.hasMatchingTag("Action", "Withdraw"), function(msg)
    print("Withdraw")
    ao.send({ Target = msg.From, Data = "Withdraw" })
end)
Handlers.add("Conclude", Handlers.utils.hasMatchingTag("Action", "Conclude"), function(msg)
    print("Conclude")
    ao.send({ Target = msg.From, Data = "Conclude" })
end)
Handlers.add("GetMarketInfo", Handlers.utils.hasMatchingTag("Action", "GetMarketInfo"), function(msg)
    print("GetMarketInfo")
    ao.send({ Target = msg.From, Data = json.encode(MarketInfo) })
end)
